In [11]:
import torch
import numpy as np

In [13]:
#创建一个Tensor
t1 = torch.Tensor([1,2,3])

In [14]:
t1 #整型变成了浮点型

tensor([1., 2., 3.])

In [15]:
#使用numpy创建一个数组
arry1 = np.arange(12).reshape(3,4)

In [16]:
arry1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
#将numpy数组转成Tensor
torch.Tensor(arry1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])